config/routes.rb
Rails.application.routes.draw do
  resources :appointments, only: [:index, :create, :update]
  root :to => 'home#index'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  def get_data
    {
      "title": title,
      "id": id,
      "start": formatted_date(start_at),
      "end": formatted_date(end_at)
    }
  end

  def formatted_date(date)
    date.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.where('start_at >= ? and end_at <= ?', parsed_date(params[:start]), parsed_date(params[:end]))
    data = @appointments.map(&:get_data)    
    render :json => data, :status => :ok
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.save
    redirect_to root_path
  end

  def update
    @appointment = Appointment.find(params[:id])
    params.delete(:id)
    @appointment.attributes = appointment_params
    @appointment.save
    render nothing: true
  end

  def appointment_params
    params.permit(:title, :start_at, :end_at)
  end

  def parsed_date(date)
    Date.parse(date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
#calendar

#eventModal.modal.fade{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} x
        %h4.modal-title Create Appointment
      .modal-body
        = form_tag appointments_path, method: 'post', class: 'form-horizontal' do
          .form-group
            = label_tag :title, "Title", class: 'control-label col-sm-2'
            .col-sm-10
              = text_field_tag :title, '',class: 'form-control'
              = hidden_field_tag :start_at
              = hidden_field_tag :end_at

          .form-group
            = label_tag :when, "When:", class: 'control-label col-sm-2'
            #when.col-sm-10{:style => "margin-top:5px;"}
          .form-group
            .col-sm-offset-2.col-sm-10
              = submit_tag 'Save'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlotBooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>